# Simple workflow for deploying static content to GitHub Pages
name: Deploy Notebooks to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install jupyter nbconvert
        
      - name: Convert notebooks to HTML
        run: |
          mkdir -p docs
          find . -name "*.ipynb" -exec jupyter nbconvert --to html --output-dir docs {} \;
          
      - name: Create index page
        run: |
          echo "<h1>Mis Notebooks</h1>" > docs/index.html
          echo "<ul>" >> docs/index.html
          for file in docs/*.html; do
            if [ "$(basename "$file")" != "index.html" ]; then
              name=$(basename "$file" .html)
              echo "<li><a href=\"$name.html\">$name</a></li>" >> docs/index.html
            fi
          done
          echo "</ul>" >> docs/index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
